version: '3'
services:
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=knoct
      - TZ=Asia/Kolkata

  redis:
    image: redis:6.2.5
    volumes:
      - ./docker/redis_data:/data
    ports:
      - "6379:6379"
  
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ./docker/run.sh
    volumes:
      - .:/knoct-rails
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
