development:
  host: db
  adapter: postgresql
  encoding: unicode
  database: knoct
  pool: 10
  username: root
  password: password

test:
  host: db
  adapter: postgresql
  encoding: unicode
  database: knoct
  pool: 5
  username: root
  password: password
